title: "Sumeeth Tewar — Systems Architect"
email: sumeet.tewar@gmail.com
description: "Architecture leadership: strategy, governance, and applied systems thinking."
url: "https://sumeethtewar.github.io"
baseurl: "" # leave blank for user.github.io sites
theme: "minima"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# navigation
#header:
#  logo: "/assets/images/logo.svg"

permalink: /:title/

# minimal settings to start
#paginate: 5
